#add_subdirectory("")#
add_subdirectory("Plugin_Base64Converter")#添加Base64转换工具插件
add_subdirectory("Plugin_BinaryViewer")#添加二进制查看器插件
add_subdirectory("Plugin_ChartDemo")#添加图表示例插件
add_subdirectory("Plugin_CryptologyTool")#添加加密解密示例插件
add_subdirectory("Plugin_CustomDelegateDemo")#添加自定义委托示例插件
add_subdirectory("Plugin_DatabaseVisualizationTool")#添加数据库可视化工具插件
add_subdirectory("Plugin_GraphicsViewDemo")#添加2D场景绘制示例插件
add_subdirectory("Plugin_IdentifyCardNumberChecker")#添加身份证号码验证工具插件
add_subdirectory("Plugin_JsonVisualEditor")#添加Json编辑器插件
add_subdirectory("Plugin_MarkDownEditor")#添加Markdown编辑器插件
add_subdirectory("Plugin_MediaPlayer")#添加媒体播放器插件
add_subdirectory("Plugin_NetworkTool")#添加网络测试工具插件
